# Generated by Django 3.2.8 on 2021-10-31 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trash',
            old_name='lon',
            new_name='lng',
        ),
    ]
